leavedays/Controllers/AdminController.cs
using leavedays.Models;
using leavedays.Models.Repository.Interfaces;
using leavedays.Models.ViewModel;
using leavedays.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using leavedays.Models.ViewModels.License;
using Microsoft.Win32;
using System.Text;
using System.IO;
using CsvHelper;
using CsvHelper.Configuration;
using Hangfire;

namespace leavedays.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        private readonly CompanyService companyService;
        private readonly InvoiceService invoiceService;
        private readonly IUserRepository userRepository;
        private readonly ILicenseRepository licenseRepository;
        private readonly ICompanyRepository companyRepository;
        private readonly IInvoiceRepository invoiceRepository;
        private readonly IModuleRepository moduleRepository;
        private readonly IModuleChangeRepository moduleChangeRepository;
        private readonly LicenseService licenseService;
        private readonly IDefaultModuleRepository defaultModuleRepository;
        private readonly IDefaultLicenseRepository defaultLicenseRepository;
        private readonly EmailSenderService emailService;


        public AdminController(
           IModuleChangeRepository moduleChangeRepository,
           CompanyService companyService,
           IUserRepository userRepository,
           LicenseService licenseService,
           ILicenseRepository licenseRepository,
           ICompanyRepository companyRepository,
           IInvoiceRepository invoiceRepository,
           IModuleRepository moduleRepository,
           InvoiceService invoiceService,
           IDefaultModuleRepository defaultModuleRepository,
           IDefaultLicenseRepository defaultLicenseRepository,
           EmailSenderService emailService)
        {
            this.emailService = emailService;
            this.moduleChangeRepository = moduleChangeRepository;
            this.licenseService = licenseService;
            this.userRepository = userRepository;
            this.companyService = companyService;
            this.licenseRepository = licenseRepository;
            this.companyRepository = companyRepository;
            this.invoiceRepository = invoiceRepository;
            this.moduleRepository = moduleRepository;
            this.invoiceService = invoiceService;
            this.defaultModuleRepository = defaultModuleRepository;
            this.defaultLicenseRepository = defaultLicenseRepository;
        }



        public ActionResult Index()
        {
            return View();
        }


        [Authorize(Roles = Roles.FinanceAdmin)]
        [HttpGet]
        public ActionResult Invoices()
        {
            var invoices = invoiceService.GetInvoices();
            var result = invoices.Select(m => new InvoiceView
            {
                Id = m.Id,
                CompanyName = companyService.GetById(m.Company.Id).FullName,
                RecieveDate = m.RecieveDate
            });
            return View(result);
        }

        [Authorize(Roles = Roles.FinanceAdmin)]
        [HttpPost]
        public ActionResult DeleteInvoice(int id)
        {
            var invoice = invoiceRepository.GetById(id);
            invoice.isDeleted = true;
            invoiceRepository.Save(invoice);
            return RedirectToAction("Invoices");
        }

        [Authorize(Roles = Roles.FinanceAdmin)]
        [HttpPost]
        public ActionResult DeleteInvoices(string ids)
        {
            string[] idStringMass = ids.Split(' ');
            int[] idIntMass = new int[idStringMass.Length];
            for (int i = 0; i < idIntMass.Length; i++)
            {
                idIntMass[i] = int.Parse(idStringMass[i]);
            }
            var invoices = invoiceRepository.GetByIds(idIntMass);
            for (int i = 0; i < invoices.Count; i++)
            {
                invoices[i].isDeleted = true;
            }
            invoiceRepository.Save(invoices);
            return RedirectToAction("Invoices");
        }

        [Authorize]
        [HttpPost]
        public FileResult DownloadInvoice(int id)
        {
            InvoiceForDownload invoice = invoiceService.CreateInvoiceForDownload(id);
            var file = invoiceService.GetInvoiceFile(new List<InvoiceForDownload>() { invoice });
            return File(file, "text/csv", "Invoice" + id.ToString() + ".csv");
        }

        [Authorize]
        [HttpPost]
        public FileResult DownloadInvoices(string[] ids)
        {
            var invoices = invoiceService.CreateInvoicesForDownload(ids.Select(m => int.Parse(m)).ToArray());
            var file = invoiceService.GetInvoiceFile(invoices);
            return File(file, "text/csv", "Invoices.csv");
        }

        public ActionResult CreateTestInvoice()
        {
            var user = userRepository.GetById(User.Identity.GetUserId<int>());
            var invoice = new Invoice
            {
                Company = companyRepository.GetById(user.CompanyId),
                RecieveDate = DateTime.Now
            };
            invoiceRepository.Save(invoice);
            return Content(invoice.Id.ToString());
        }

        [Authorize(Roles = Roles.FinanceAdmin)]
        [HttpGet]
        public ActionResult LicensesInfo()
        {
            return View("ShowLicensesInfo", licenseService.GetLicenseInfoList());
        }

        //-------
        [Authorize(Roles = Roles.Customer)]
        [HttpGet]
        public ActionResult EnableModules()
        {
            var model = licenseService.GetLicenseInfo(User.Identity.GetUserId<int>());
            model.ModulesInfoList = licenseService.GetModulesShortInfo(model.License, false);
            return View(model);
        }

        [Authorize(Roles = Roles.Customer)]
        [HttpPost]
        public ActionResult EnableModules(List<ModuleShortInfo> model)
        {
            var licenseResult = licenseService.EditModules(User.Identity.GetUserId<int>(), model, true);
            if (licenseResult.Succed)
            {
                var license = licenseResult.GetResult();
                var modulesInfo = licenseService.GetModulesShortInfo(license, false);
                return PartialView("SwitchModules", modulesInfo);
            }
            return Content("Error");
        }


        [Authorize(Roles = Roles.Customer)]
        [HttpGet]
        public ActionResult DisableModules()
        {
            var model = licenseService.GetLicenseInfo(User.Identity.GetUserId<int>());
            model.ModulesInfoList = licenseService.GetModulesShortInfo(model.License, true);
            return View(model);
        }

        [Authorize(Roles = Roles.Customer)]
        [HttpPost]
        public ActionResult DisableModules(List<ModuleShortInfo> model)
        {

            var licenseResult = licenseService.EditModules(User.Identity.GetUserId<int>(), model, false);
            if (licenseResult.Succed)
            {
                var license = licenseResult.GetResult();
                var modulesInfo = licenseService.GetModulesShortInfo(license, true);

                return PartialView("SwitchModules", modulesInfo);
            }
            return Content("Error");
        }

        //-------
        [Authorize(Roles = Roles.Customer)]
        [HttpGet]
        public ActionResult AddLicenseSeats()
        {
            var model = licenseService.GetLicenseInfo(User.Identity.GetUserId<int>());
            return View(model);
        }

        [Authorize(Roles = Roles.Customer)]
        [HttpPost]
        public JsonResult AddLicenseSeats(int count)
        {
            var result = licenseService.EditLicenseSeats(User.Identity.GetUserId<int>(), count);
            return Json(result);
        }

        [Authorize(Roles = Roles.Customer)]
        [HttpGet]
        public ActionResult RemoveLicenseSeats()
        {
            var model = licenseService.GetLicenseInfo(User.Identity.GetUserId<int>());
            return View(model);
        }

        [Authorize(Roles = Roles.Customer)]
        [HttpPost]
        public JsonResult RemoveLicenseSeats(int count)
        {
            var result = licenseService.EditLicenseSeats(User.Identity.GetUserId<int>(), -count);
            return Json(result);
        }
        //-------




        [Authorize(Roles = Roles.FinanceAdmin)]
        [HttpGet]
        public JsonResult GetSearchInvoice(string search = "")
        {
            var result = licenseService.GetSearchedLicenseInfo(search);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "financeadmin")]
        [HttpGet]
        public JsonResult GetAdwenchedSearchInvoice(Models.ViewModel.SearchOption option)
        {
            var result = licenseService.GetAdwenchedSearchLicenseInfo(option);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = Roles.FinanceAdmin)]
        [HttpGet]
        public ActionResult Modules()
        {
            return View(licenseService.GetModulesInfo());
        }

        [Authorize(Roles = Roles.FinanceAdmin)]
        [HttpGet]
        public ActionResult ModuleInfo(int id)
        {
            return View(licenseService.GetModuleInfo(id));
        }

        [Authorize(Roles = Roles.FinanceAdmin)]
        [HttpGet]
        public ActionResult EditModule(int id)
        {
            var module = defaultModuleRepository.GetById(id);
            var moduleLicenses = defaultLicenseRepository.GetByModuleId(module.Id);
            var allLicenses = defaultLicenseRepository.GetAll();
            EditModuleModel editModule = new EditModuleModel()
            {
                Id = module.Id,
                Name = module.Name,
                Description = module.Description,
                Price = module.Price,

leavedays/Controllers/ModuleController.cs
using leavedays.Models;
using leavedays.Models.EditModel;
using leavedays.Models.ViewModel;
using leavedays.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using leavedays.Models.Repository.Interfaces;
using leavedays.Models.ViewModels.License;
using System.Text;

namespace leavedays.Controllers
{
    public class ModuleController : Controller
    {
        private readonly CompanyService companyService;
        private readonly InvoiceService invoiceService;
        private readonly IUserRepository userRepository;
        private readonly ILicenseRepository licenseRepository;
        private readonly ICompanyRepository companyRepository;
        private readonly IInvoiceRepository invoiceRepository;
        private readonly IModuleRepository moduleRepository;
        private readonly LicenseService licenseService;
        private readonly IDefaultModuleRepository defaultModuleRepository;
        private readonly IDefaultLicenseRepository defaultLicenseRepository;
        private readonly RequestService requestService;
        private readonly UserManager<AppUser, int> userManager;


        public ModuleController(RequestService requestService,
           UserManager<AppUser, int> userManager,
           CompanyService companyService,
           IUserRepository userRepository,
           LicenseService licenseService,
           ILicenseRepository licenseRepository,
           ICompanyRepository companyRepository,
           IInvoiceRepository invoiceRepository,
           IModuleRepository moduleRepository,
           InvoiceService invoiceService,
           IDefaultModuleRepository defaultModuleRepository,
           IDefaultLicenseRepository defaultLicenseRepository)
        {
            this.licenseService = licenseService;
            this.userRepository = userRepository;
            this.licenseRepository = licenseRepository;
            this.companyRepository = companyRepository;
            this.invoiceRepository = invoiceRepository;
            this.moduleRepository = moduleRepository;
            this.invoiceService = invoiceService;
            this.defaultModuleRepository = defaultModuleRepository;
            this.defaultLicenseRepository = defaultLicenseRepository;
            this.userManager = userManager;
            this.requestService = requestService;
        }


        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            var currentUser = await userManager.FindByIdAsync(User.Identity.GetUserId<int>());
            if (currentUser == null) return RedirectToAction("Index", "Home");
            EditRequest request = new EditRequest()
            {
                Status = "New",
                UserId = currentUser.Id,
                CompanyId = currentUser.CompanyId,
            };
            return View(request);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(EditRequest request)
        {
            if (!ModelState.IsValid) RedirectToAction("Index", "Home");
            requestService.Save(request);
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> ConfirmNew()
        {
            var currentUser = await userManager.FindByIdAsync(User.Identity.GetUserId<int>());
            if(User.IsInRole("customer") && User.IsInRole("manager"))
            {
                return View("RequestPanel", requestService.GetInProgressRequest(currentUser.CompanyId).OrderBy(model => model.IsAccepted));
            }
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        [HttpPost]
        public ActionResult Accept(int Id, string returnUrl = "")
        {
            requestService.Accept(Id);
            if (string.IsNullOrEmpty(returnUrl)) return View("Index", "Home");
            return Redirect(returnUrl);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Reject(int Id, string returnUrl = "")
        {
            requestService.Reject(Id);
            if (string.IsNullOrEmpty(returnUrl)) return View("Index", "Home");
            return Redirect(returnUrl);
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> ShowConfirmed()
        {
            var currentUser = await userManager.FindByIdAsync(User.Identity.GetUserId<int>());
            if (User.IsInRole("customer") && User.IsInRole("manager"))
            {
                return View("ConfirmedRequest", requestService.GetConfirmedRequest(currentUser.CompanyId).OrderBy(model => model.IsAccepted));
            }
            return View("Index", "Home");
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> ShowSended()
        {
            var currentUser = await userManager.FindByIdAsync(User.Identity.GetUserId<int>());
            if (currentUser == null) return RedirectToAction("Index", "Home");
            return View("UsersRequest", requestService.GetSendedByUserId(currentUser.Id));
        }

        public ActionResult eOwerview()
        {
            return View();
        }
        public ActionResult cOverview()
        {
            return View();
        }
        public ActionResult Pending()
        {
            return View();
        }

        [Authorize(Roles = "customer")]
        [HttpGet]
        public async Task<ActionResult> licenceInfo()
        {
            var user = userRepository.GetById(User.Identity.GetUserId<int>());
            if (user == null) return RedirectToAction("Index", "Home");

            var companyId = user.CompanyId;
            var company = companyRepository.GetById(companyId);
            var licenseId = company.LicenseId;
            var license = licenseRepository.GetById(licenseId);
            var disabledModules = moduleRepository.GetByLicenseId(licenseId, false);
            var defaultModules = disabledModules.Select(module => defaultModuleRepository.GetById(module.Id)).ToList();

            var model = new EditLicenseModules()
            {
                LicenseName = defaultLicenseRepository.GetById(license.DefaultLicenseId).Name,
                LicenseCode = license.LicenseCode,
                Modules = defaultModules
            };


            return View(model);
        }
    }
}

leavedays/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <style>
        #nav ul ul {
            display: none;
            margin-left: 25px;
            padding-left: 2px;
            width: 220px;
        }
    </style>
    <meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
    <title>
        home
    </title>
    <link type="text/css" href="~/Content/Style.css" rel="stylesheet">
    <link href="~/Content/datepicker.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
</head>
<body>
    <div id="banner_div">
        <img alt="leaveday banner" src="~/Content/img/top_banner.jpg">
    </div>
    <div id="topbar_div">
        <div>
            <img src="~/Content/img/logo-leavedays-small.png" alt="" class="pull-left">
            <div id="leftWelcome" class="pull-left">
                System of registration
                Here should be your name!
            </div>
            <div id="rightWelcome">
                <div id="rightWelcomeText">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <text>Wellcome</text>
                        @User.Identity.Name
                        @Html.ActionLink("Log Out", "LogOff", "Account")
                    }
                    else
                    {
                        <span style="margin-right: 5px;">@Html.ActionLink("Log In", "Login", "Account")</span>
                        <span>@Html.ActionLink("Register", "Register", "Account")</span>
                    }
                </div>
                <div id="rightWelcomeHelpImg">
                    <img src="~/Content/img/helpicon_gray.gif" alt="Help" style="cursor: pointer;" onclick="window.open('http://support.leavedays.com&#39;, &#39;CustomPopUp&#39;, &#39;width=800, height=600, scrollbars=1, menubar=no, resizable=yes')">
                </div>
            </div>
        </div>
        <br>
    </div>
    <div id="main_div">
        <div id="menu-div" style="display: block;">

            <div id="masterDiv" class="menu-open" style="">
                <a id="homemenu" class="homemenu active-menu-item" href="@Url.Action("Index", "Home")" style="display: block;">
                    <i class="menu-icon menu-icon-home pull-left"></i>
                    <span class="pull-left">домашняя страница</span>
                </a>
                <div id="main_div">
                    <div id="menu-div" style="display: block;">
                        <div id="masterDiv" class="menu-open" style="">

                            <div class="left" id="nav" style="font-size: 150%">
                                <ul>
                                    <li>
                                        Customer
                                        <ul>
                                            @if (User.Identity.IsAuthenticated)
                                            {
                                                <li>
                                                    @Html.ActionLink("Request", "Create", "Module")
                                                </li>
                                            }
                                            
                                             @if (User.Identity.IsAuthenticated)
                                             {
                                                 <li>
                                                 @Html.ActionLink("for consideration", "ConfirmNew", "Module")
                                                  </li>
                                              }
                                              @if (User.IsInRole("financeadmin"))
                                              {
                                                   <li>
                                                   @Html.ActionLink("Create Company", "CreateCompany", "Account")
                                                   </li>
                                              }
                                              @if (User.IsInRole("customer"))
                                              {
                                                  <li>
                                                  @Html.ActionLink("Create Emplyee", "CreateEmployee", "Account")
                                                  </li>
                                              }
                                              @if (User.IsInRole("customer"))
                                              {
                                                <li>@Html.ActionLink("Add modules to license", "EnableModules", "Admin")</li>
                                                <li>@Html.ActionLink("Remove license's modules", "DisableModules", "Admin")</li>
                                                <li>@Html.ActionLink("Add seats to license", "AddLicenseSeats", "Admin")</li>
                                                <li>@Html.ActionLink("Remove seats from license", "RemoveLicenseSeats", "Admin")</li>
                                                <li>
                                                    @Html.ActionLink("Download next invoice", "NextInvoice", "Admin")
                                                </li>
                                              }

                                        </ul>

                                    </li>
    
                                    @if (User.IsInRole("financeadmin")) {

                                    <li>
                                        Finance Admin
                                        <ul>
                                            <li>@Html.ActionLink("Invoices", "Invoices", "Admin")</li>
                                            <li>@Html.ActionLink("Modules", "Modules", "Admin")</li>
                                            <li>@Html.ActionLink("Customers", "LicensesInfo", "Admin")</li>
                                            <li>@Html.ActionLink("Create new module", "CreateModule", "Admin")</li>
                                            <li>@Html.ActionLink("Create new license", "CreateLicense", "Admin")</li>
                                        </ul>
                                    </li>}
                                    <li>
                                        Other
                                        <ul>
                                            <li>@Html.ActionLink("Pending requests", "Pending", "Module")</li>
                                            <li>@Html.ActionLink("Create request", "Create", "Module")</li>
                                            <li>@Html.ActionLink("for consideration", "ConfirmNew", "Module")</li>
                                            <li>@Html.ActionLink("Confirmed requests", "ShowConfirmed", "Module")</li>
                                            <li>@Html.ActionLink("Sended requests", "ShowSended", "Module")</li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

                    <div id="content-div" style="display: block;">
                        <div id="error-div" class="ui-state-error padded c-hide">
                        </div>
                        <div id="departmentCapacity"></div>
                        <div>
                            @RenderBody()
                        </div>
                        <br>
                        <br>
                    </div>
                    <br>
                </div>
                <br>
                <div id="footer_div">
                    <span id="leftFooter"> Number of licenses</span>
                    <span id="rightFooter">Some numbers(2017.73.6283.20254)</span>
                    @*<script type="text/javascript" src="~/Scripts/asset(1).js"></script>
            <script src="~/Scripts/analytics.js"></script>
            <script src="~/Scripts/nr-1026.min.js"></script>*@
                    <script>
                        $('#nav ul li')
                        .css({ cursor: "pointer" })
                        .on('click', function () {
                            $(this).find('ul').toggle();
                        })
                    </script>
</body>
</html>